name: SubModuleUpdator

# Run this workflow a new commit pushed to /natecostello/content_test
on:
  repository_dispatch:
   types: [my-test]

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.PAT_MY_TOKEN }}
          submodules: recursive
