name: Super-Linter

# Run this workflow a new commit pushed to /natecostello/content_test
on:
  repository_dispatch:
   types: [my-test]

jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
